/**
 * EPH XML builder — web port of farm-app's ephExport.service.ts
 * Generates XML for Portal farmáře POR / full evidence upload.
 * MEDIUM CONFIDENCE: tag names from domain knowledge — verify before production use.
 */

export interface EphRecord {
  id: string;
  parcel_id: string;
  operation_type: string;
  operation_date: string;
  crop: string | null;
  fertilizer_name: string | null;
  n_kg_per_ha: number | null;
  p_kg_per_ha: number | null;
  k_kg_per_ha: number | null;
  dose_kg_per_ha: number | null;
  dose_l_per_ha: number | null;
  area_ha: number | null;
  por_product_name: string | null;
  por_registration_number?: string | null;
  growth_stage?: string | null;
  notes: string | null;
  // enriched
  parcel_name?: string | null;
  lpis_code?: string | null;
}

export interface EphFarm {
  registrationNumber: string;
  name: string;
}

function escapeXml(s: string | null | undefined): string {
  if (!s) return '';
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function fmtDate(iso: string): string {
  const [y, m, d] = iso.split('-');
  return `${d}.${m}.${y}`;
}

function buildPostrik(r: EphRecord): string {
  return `    <Postrik>
      <DatumPostriku>${escapeXml(fmtDate(r.operation_date))}</DatumPostriku>
      <KodDPB>${escapeXml(r.lpis_code ?? r.parcel_id)}</KodDPB>
      <Kultura>${escapeXml(r.crop ?? '')}</Kultura>
      <VymeraPlochy>${(r.area_ha ?? 0).toFixed(4)}</VymeraPlochy>
      <NazevPPP>${escapeXml(r.por_product_name ?? '')}</NazevPPP>
      <RegistracniCisloPPP>${escapeXml(r.por_registration_number ?? '')}</RegistracniCisloPPP>
      <DavkaLHa>${(r.dose_l_per_ha ?? 0).toFixed(2)}</DavkaLHa>
      <FazePlodiny>${escapeXml(r.growth_stage ?? '')}</FazePlodiny>
      <Plodina>${escapeXml(r.crop ?? '')}</Plodina>
      <Operator></Operator>
      <Poznamka>${escapeXml(r.notes ?? '')}</Poznamka>
    </Postrik>`;
}

function buildHnojeni(r: EphRecord): string {
  return `    <Hnojeni>
      <DatumHnojeni>${escapeXml(fmtDate(r.operation_date))}</DatumHnojeni>
      <KodDPB>${escapeXml(r.lpis_code ?? r.parcel_id)}</KodDPB>
      <Plodina>${escapeXml(r.crop ?? '')}</Plodina>
      <VymeraPlochy>${(r.area_ha ?? 0).toFixed(4)}</VymeraPlochy>
      <NazevHnojiva>${escapeXml(r.fertilizer_name ?? '')}</NazevHnojiva>
      <DavkaKgHa>${(r.dose_kg_per_ha ?? 0).toFixed(2)}</DavkaKgHa>
      <NKgHa>${(r.n_kg_per_ha ?? 0).toFixed(2)}</NKgHa>
      <PKgHa>${(r.p_kg_per_ha ?? 0).toFixed(2)}</PKgHa>
      <KKgHa>${(r.k_kg_per_ha ?? 0).toFixed(2)}</KKgHa>
      <Poznamka>${escapeXml(r.notes ?? '')}</Poznamka>
    </Hnojeni>`;
}

function buildSeti(r: EphRecord): string {
  return `    <Seti>
      <DatumSeti>${escapeXml(fmtDate(r.operation_date))}</DatumSeti>
      <KodDPB>${escapeXml(r.lpis_code ?? r.parcel_id)}</KodDPB>
      <Plodina>${escapeXml(r.crop ?? '')}</Plodina>
      <VymeraPlochy>${(r.area_ha ?? 0).toFixed(4)}</VymeraPlochy>
      <DavkaKgHa>${(r.dose_kg_per_ha ?? 0).toFixed(2)}</DavkaKgHa>
      <Poznamka>${escapeXml(r.notes ?? '')}</Poznamka>
    </Seti>`;
}

function buildSklizen(r: EphRecord): string {
  return `    <Sklizen>
      <DatumSklizne>${escapeXml(fmtDate(r.operation_date))}</DatumSklizne>
      <KodDPB>${escapeXml(r.lpis_code ?? r.parcel_id)}</KodDPB>
      <Plodina>${escapeXml(r.crop ?? '')}</Plodina>
      <VymeraPlochy>${(r.area_ha ?? 0).toFixed(4)}</VymeraPlochy>
      <Poznamka>${escapeXml(r.notes ?? '')}</Poznamka>
    </Sklizen>`;
}

function buildOrba(r: EphRecord): string {
  return `    <Orba>
      <DatumOrby>${escapeXml(fmtDate(r.operation_date))}</DatumOrby>
      <KodDPB>${escapeXml(r.lpis_code ?? r.parcel_id)}</KodDPB>
      <VymeraPlochy>${(r.area_ha ?? 0).toFixed(4)}</VymeraPlochy>
      <Poznamka>${escapeXml(r.notes ?? '')}</Poznamka>
    </Orba>`;
}

export function buildEphXml(records: EphRecord[], farm: EphFarm): string {
  const sections = records
    .map((r) => {
      switch (r.operation_type) {
        case 'postrik': return buildPostrik(r);
        case 'hnojeni': return buildHnojeni(r);
        case 'seti': return buildSeti(r);
        case 'sklizen': return buildSklizen(r);
        case 'orba': return buildOrba(r);
        default: return null;
      }
    })
    .filter(Boolean)
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- EPH export generated by FarmaSamec -->
<EPH_Export xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Farma ico="${escapeXml(farm.registrationNumber)}" nazev="${escapeXml(farm.name)}">${sections ? '\n' + sections + '\n  ' : ''}
  </Farma>
</EPH_Export>`;
}
