/**
 * Predefined templates for common Czech agricultural machinery.
 * Used in MachineFormModal to pre-fill the form.
 */

export interface MachineTemplate {
  name: string;
  type: string;
  powerHp?: number;
  workWidthM?: number;
  loadCapacityT?: number;
  overlapCm?: number;       // default overlap for guidance lines
  workSpeedKmh?: number;    // typical working speed
  fuelConsumptionLh?: number; // typical fuel consumption L/h
}

export interface MachineTemplateGroup {
  label: string;
  emoji: string;
  items: MachineTemplate[];
}

export const MACHINE_TEMPLATE_GROUPS: MachineTemplateGroup[] = [
  {
    label: 'Traktory',
    emoji: '🚜',
    items: [
      { name: 'Zetor Major 80', type: 'tractor', powerHp: 80 },
      { name: 'Zetor Proxima 100', type: 'tractor', powerHp: 100 },
      { name: 'Zetor Forterra 140 HD', type: 'tractor', powerHp: 140 },
      { name: 'Zetor Crystal 160', type: 'tractor', powerHp: 160 },
      { name: 'John Deere 5090R', type: 'tractor', powerHp: 90 },
      { name: 'John Deere 5100R', type: 'tractor', powerHp: 100 },
      { name: 'John Deere 5115M', type: 'tractor', powerHp: 115 },
      { name: 'John Deere 6090M', type: 'tractor', powerHp: 90 },
      { name: 'John Deere 6100M', type: 'tractor', powerHp: 100 },
      { name: 'John Deere 6110M', type: 'tractor', powerHp: 110 },
      { name: 'John Deere 6120M', type: 'tractor', powerHp: 120 },
      { name: 'John Deere 6130M', type: 'tractor', powerHp: 130 },
      { name: 'John Deere 6140M', type: 'tractor', powerHp: 140 },
      { name: 'John Deere 6155M', type: 'tractor', powerHp: 155 },
      { name: 'John Deere 6110R', type: 'tractor', powerHp: 110 },
      { name: 'John Deere 6120R', type: 'tractor', powerHp: 120 },
      { name: 'John Deere 6130R', type: 'tractor', powerHp: 130 },
      { name: 'John Deere 6145R', type: 'tractor', powerHp: 145 },
      { name: 'John Deere 6155R', type: 'tractor', powerHp: 155 },
      { name: 'John Deere 6175R', type: 'tractor', powerHp: 175 },
      { name: 'John Deere 6195R', type: 'tractor', powerHp: 195 },
      { name: 'John Deere 6215R', type: 'tractor', powerHp: 215 },
      { name: 'John Deere 6250R', type: 'tractor', powerHp: 250 },
      { name: 'John Deere 7R 270', type: 'tractor', powerHp: 270 },
      { name: 'John Deere 7R 290', type: 'tractor', powerHp: 290 },
      { name: 'John Deere 7R 310', type: 'tractor', powerHp: 310 },
      { name: 'John Deere 7R 330', type: 'tractor', powerHp: 330 },
      { name: 'John Deere 8R 310', type: 'tractor', powerHp: 310 },
      { name: 'John Deere 8R 340', type: 'tractor', powerHp: 340 },
      { name: 'John Deere 8R 370', type: 'tractor', powerHp: 370 },
      { name: 'New Holland T4.95', type: 'tractor', powerHp: 95 },
      { name: 'New Holland T4.110', type: 'tractor', powerHp: 110 },
      { name: 'New Holland T5.100', type: 'tractor', powerHp: 100 },
      { name: 'New Holland T5.110', type: 'tractor', powerHp: 110 },
      { name: 'New Holland T5.120', type: 'tractor', powerHp: 120 },
      { name: 'New Holland T5.130', type: 'tractor', powerHp: 130 },
      { name: 'New Holland T5.140', type: 'tractor', powerHp: 140 },
      { name: 'New Holland T6.120', type: 'tractor', powerHp: 120 },
      { name: 'New Holland T6.140', type: 'tractor', powerHp: 140 },
      { name: 'New Holland T6.155', type: 'tractor', powerHp: 155 },
      { name: 'New Holland T6.165', type: 'tractor', powerHp: 165 },
      { name: 'New Holland T6.175', type: 'tractor', powerHp: 175 },
      { name: 'New Holland T6.180', type: 'tractor', powerHp: 180 },
      { name: 'New Holland T7.190', type: 'tractor', powerHp: 190 },
      { name: 'New Holland T7.210', type: 'tractor', powerHp: 210 },
      { name: 'New Holland T7.230', type: 'tractor', powerHp: 230 },
      { name: 'New Holland T7.250', type: 'tractor', powerHp: 250 },
      { name: 'New Holland T7.270', type: 'tractor', powerHp: 270 },
      { name: 'New Holland T7.290', type: 'tractor', powerHp: 290 },
      { name: 'New Holland T8.320', type: 'tractor', powerHp: 320 },
      { name: 'New Holland T8.350', type: 'tractor', powerHp: 350 },
      { name: 'New Holland T8.380', type: 'tractor', powerHp: 380 },
      { name: 'Case IH Puma 165', type: 'tractor', powerHp: 165 },
      { name: 'Case IH Magnum 280', type: 'tractor', powerHp: 280 },
      { name: 'Fendt 516 Vario', type: 'tractor', powerHp: 165 },
      { name: 'Fendt 718 Vario', type: 'tractor', powerHp: 180 },
      { name: 'Claas Arion 550', type: 'tractor', powerHp: 150 },
      { name: 'Claas Axion 870', type: 'tractor', powerHp: 270 },
      { name: 'Kubota M7-152', type: 'tractor', powerHp: 152 },
      { name: 'Deutz-Fahr 6130 TTV', type: 'tractor', powerHp: 130 },
      { name: 'Valtra T174', type: 'tractor', powerHp: 175 },
    ],
  },
  {
    label: 'Kombajny',
    emoji: '🌾',
    items: [
      { name: 'Claas Lexion 750', type: 'combine', powerHp: 390, workWidthM: 9.0 },
      { name: 'Claas Tucano 580', type: 'combine', powerHp: 326, workWidthM: 7.5 },
      { name: 'Claas Avero 240', type: 'combine', powerHp: 175, workWidthM: 5.4 },
      { name: 'John Deere S770', type: 'combine', powerHp: 473, workWidthM: 9.15 },
      { name: 'John Deere W540', type: 'combine', powerHp: 254, workWidthM: 7.6 },
      { name: 'New Holland CR9.90', type: 'combine', powerHp: 645, workWidthM: 10.7 },
      { name: 'Case IH Axial-Flow 7150', type: 'combine', powerHp: 374, workWidthM: 9.15 },
      { name: 'Fendt 6335 C Cemos', type: 'combine', powerHp: 335, workWidthM: 9.0 },
    ],
  },
  {
    label: 'Postřikovače',
    emoji: '🌿',
    items: [
      { name: 'Horsch Leeb 4 PT (18 m)', type: 'sprayer', workWidthM: 18 },
      { name: 'Horsch Leeb 6 PT (24 m)', type: 'sprayer', workWidthM: 24 },
      { name: 'Horsch Leeb 6 PT (27 m)', type: 'sprayer', workWidthM: 27 },
      { name: 'Amazone UX 5200 (24 m)', type: 'sprayer', workWidthM: 24 },
      { name: 'Amazone UX 6200 (27 m)', type: 'sprayer', workWidthM: 27 },
      { name: 'John Deere R4045 (27 m)', type: 'sprayer', workWidthM: 27 },
      { name: 'Lemken Vega 12 (24 m)', type: 'sprayer', workWidthM: 24 },
      { name: 'Hardi Navigator 4000 (24 m)', type: 'sprayer', workWidthM: 24 },
      { name: 'Berthoud Tracker 6040 (24 m)', type: 'sprayer', workWidthM: 24 },
    ],
  },
  {
    label: 'Secí stroje',
    emoji: '🌱',
    items: [
      { name: 'Horsch Pronto 3 DC (3 m)', type: 'seeder', workWidthM: 3.0 },
      { name: 'Horsch Pronto 6 DC (6 m)', type: 'seeder', workWidthM: 6.0 },
      { name: 'Amazone D9 3000 (3 m)', type: 'seeder', workWidthM: 3.0 },
      { name: 'Amazone Cirrus 6001 (6 m)', type: 'seeder', workWidthM: 6.0 },
      { name: 'Väderstad Rapid 300S (3 m)', type: 'seeder', workWidthM: 3.0 },
      { name: 'Väderstad Rapid 600S (6 m)', type: 'seeder', workWidthM: 6.0 },
      { name: 'Lemken Solitair 9 (3 m)', type: 'seeder', workWidthM: 3.0 },
      { name: 'John Deere 750A (4.5 m)', type: 'seeder', workWidthM: 4.5 },
      { name: 'Pöttinger Aerosem 3002 (3 m)', type: 'seeder', workWidthM: 3.0 },
      { name: 'Pöttinger Aerosem 4002 (4 m)', type: 'seeder', workWidthM: 4.0 },
      { name: 'Pöttinger Vitasem 302 A (3 m)', type: 'seeder', workWidthM: 3.0 },
      { name: 'Pöttinger Vitasem 402 A (4 m)', type: 'seeder', workWidthM: 4.0 },
      { name: 'Pöttinger Terrasem V 3 (3 m)', type: 'seeder', workWidthM: 3.0 },
      { name: 'Pöttinger Terrasem V 4 (4 m)', type: 'seeder', workWidthM: 4.0 },
      { name: 'Bednar FORTE 3 (3 m)', type: 'seeder', workWidthM: 3.0 },
      { name: 'Bednar FORTE 4.5 (4.5 m)', type: 'seeder', workWidthM: 4.5 },
      { name: 'Bednar OMEGA 3 (3 m)', type: 'seeder', workWidthM: 3.0 },
      { name: 'Bednar ALPHA 3 (3 m)', type: 'seeder', workWidthM: 3.0 },
    ],
  },
  {
    label: 'Pluhy',
    emoji: '🔴',
    items: [
      { name: 'Lemken Diamant 11 (4-fůrový)', type: 'plow', workWidthM: 1.4 },
      { name: 'Lemken Diamant 11 (5-fůrový)', type: 'plow', workWidthM: 1.75 },
      { name: 'Pöttinger Servo 35 M (4-fůrový)', type: 'plow', workWidthM: 1.4 },
      { name: 'Pöttinger Servo 35 Plus (4-fůrový)', type: 'plow', workWidthM: 1.4 },
      { name: 'Pöttinger Servo 45 M (4-fůrový)', type: 'plow', workWidthM: 1.4 },
      { name: 'Pöttinger Servo 45 Plus (5-fůrový)', type: 'plow', workWidthM: 1.75 },
      { name: 'Pöttinger Servo 65 (5-fůrový)', type: 'plow', workWidthM: 1.75 },
      { name: 'Kverneland 2500 I (4-fůrový)', type: 'plow', workWidthM: 1.4 },
      { name: 'Kverneland 2500 I (5-fůrový)', type: 'plow', workWidthM: 1.75 },
      { name: 'Amazone Cayros M (4-fůrový)', type: 'plow', workWidthM: 1.4 },
      { name: 'John Deere 3720 (5-fůrový)', type: 'plow', workWidthM: 1.75 },
      { name: 'Gregoire-Besson SPSL (5-fůrový)', type: 'plow', workWidthM: 1.75 },
    ],
  },
  {
    label: 'Diskery (diskové podmítače)',
    emoji: '🔄',
    items: [
      { name: 'Horsch Terrano 3 FX (3 m)', type: 'disc', workWidthM: 3.0 },
      { name: 'Horsch Terrano 4 FX (4 m)', type: 'disc', workWidthM: 4.0 },
      { name: 'Amazone Catros 3001 (3 m)', type: 'disc', workWidthM: 3.0 },
      { name: 'Amazone Catros 4001 (4 m)', type: 'disc', workWidthM: 4.0 },
      { name: 'Amazone Catros 6001 (6 m)', type: 'disc', workWidthM: 6.0 },
      { name: 'Lemken Heliodor 9 (4 m)', type: 'disc', workWidthM: 4.0 },
      { name: 'Lemken Heliodor 9 (6 m)', type: 'disc', workWidthM: 6.0 },
      { name: 'Väderstad Carrier 420 (4.2 m)', type: 'disc', workWidthM: 4.2 },
      { name: 'Väderstad Carrier 650 (6.5 m)', type: 'disc', workWidthM: 6.5 },
      { name: 'Kverneland CLC Pro (3 m)', type: 'disc', workWidthM: 3.0 },
      { name: 'Kverneland CLC Pro (4 m)', type: 'disc', workWidthM: 4.0 },
      { name: 'John Deere 2730 (4.3 m)', type: 'disc', workWidthM: 4.3 },
      { name: 'Pöttinger Terradisc 3001 (3 m)', type: 'disc', workWidthM: 3.0 },
      { name: 'Pöttinger Terradisc 4001 (4 m)', type: 'disc', workWidthM: 4.0 },
      { name: 'Pöttinger Terradisc 5001 (5 m)', type: 'disc', workWidthM: 5.0 },
      { name: 'Pöttinger Terradisc 6001 (6 m)', type: 'disc', workWidthM: 6.0 },
      { name: 'Pöttinger Synkro 3030 (3 m)', type: 'disc', workWidthM: 3.0 },
      { name: 'Pöttinger Synkro 4030 (4 m)', type: 'disc', workWidthM: 4.0 },
      { name: 'Pöttinger Terraliner 5030 (5 m)', type: 'disc', workWidthM: 5.0 },
      { name: 'Bednar SWIFTERDISC 3000 (3 m)', type: 'disc', workWidthM: 3.0 },
      { name: 'Bednar SWIFTERDISC 4500 (4.5 m)', type: 'disc', workWidthM: 4.5 },
      { name: 'Bednar SWIFTERDISC 6000 (6 m)', type: 'disc', workWidthM: 6.0 },
      { name: 'Bednar TERRADISC 4000 (4 m)', type: 'disc', workWidthM: 4.0 },
      { name: 'Bednar TERRADISC 6000 (6 m)', type: 'disc', workWidthM: 6.0 },
      { name: 'Kuhn Optimer 3000 (3 m)', type: 'disc', workWidthM: 3.0 },
    ],
  },
  {
    label: 'Radličkové podmítače / kypřiče',
    emoji: '🔄',
    items: [
      { name: 'Horsch Terrano 3 GX (3 m)', type: 'disc', workWidthM: 3.0 },
      { name: 'Horsch Terrano 4 GX (4 m)', type: 'disc', workWidthM: 4.0 },
      { name: 'Amazone Cenius 3002 (3 m)', type: 'disc', workWidthM: 3.0 },
      { name: 'Amazone Cenius 4002 (4 m)', type: 'disc', workWidthM: 4.0 },
      { name: 'Kverneland Kultistrip (3 m)', type: 'disc', workWidthM: 3.0 },
      { name: 'Lemken Kristall 9 (3 m)', type: 'disc', workWidthM: 3.0 },
      { name: 'Väderstad TopDown 300 (3 m)', type: 'disc', workWidthM: 3.0 },
    ],
  },
  {
    label: 'Podrýváky (subsoilery)',
    emoji: '⬇️',
    items: [
      { name: 'Agrisem Disc-O-Mulch Silver (3 m)', type: 'subsoiler', workWidthM: 3.0 },
      { name: 'Alpego DraCo (3 m)', type: 'subsoiler', workWidthM: 3.0 },
      { name: 'Bednar TERRALAND TO 3000 (3 m)', type: 'subsoiler', workWidthM: 3.0 },
      { name: 'Bednar TERRALAND TO 4000 (4 m)', type: 'subsoiler', workWidthM: 4.0 },
      { name: 'Bednar TERRALAND TO 5000 (5 m)', type: 'subsoiler', workWidthM: 5.0 },
      { name: 'Bednar HERCULES 3000 (3 m)', type: 'subsoiler', workWidthM: 3.0 },
      { name: 'Bednar HERCULES 4000 (4 m)', type: 'subsoiler', workWidthM: 4.0 },
      { name: 'Horsch Tiger (4 m)', type: 'subsoiler', workWidthM: 4.0 },
      { name: 'Quivogne Gyroter (3 m)', type: 'subsoiler', workWidthM: 3.0 },
      { name: 'Väderstad Cultus (4 m)', type: 'subsoiler', workWidthM: 4.0 },
    ],
  },
  {
    label: 'Válce',
    emoji: '⚫',
    items: [
      { name: 'Press válec Cambridge 3 m', type: 'roller', workWidthM: 3.0 },
      { name: 'Press válec Cambridge 4 m', type: 'roller', workWidthM: 4.0 },
      { name: 'Press válec Cambridge 6 m', type: 'roller', workWidthM: 6.0 },
      { name: 'Amazone Packer 4000 (4 m)', type: 'roller', workWidthM: 4.0 },
      { name: 'Pöttinger Lion 3002 A (3 m)', type: 'roller', workWidthM: 3.0 },
      { name: 'Pöttinger Lion 3503 A (3.5 m)', type: 'roller', workWidthM: 3.5 },
      { name: 'Pöttinger Lion 4002 A (4 m)', type: 'roller', workWidthM: 4.0 },
      { name: 'Väderstad NZ Aggressive 300 (3 m)', type: 'roller', workWidthM: 3.0 },
      { name: 'Louční válec 3 m', type: 'roller', workWidthM: 3.0 },
      { name: 'Louční válec 6 m', type: 'roller', workWidthM: 6.0 },
    ],
  },
  {
    label: 'Rozmetadla hnojiv',
    emoji: '💧',
    items: [
      { name: 'Amazone ZA-TS 3200 (28 m)', type: 'spreader', workWidthM: 28, loadCapacityT: 3.2 },
      { name: 'Amazone ZA-TS 4200 (36 m)', type: 'spreader', workWidthM: 36, loadCapacityT: 4.2 },
      { name: 'Rauch AXIS-M 20.2 (28 m)', type: 'spreader', workWidthM: 28, loadCapacityT: 2.0 },
      { name: 'Rauch AXIS-M 30.2 (36 m)', type: 'spreader', workWidthM: 36, loadCapacityT: 3.0 },
      { name: 'Kuhn Axis 50.1 (36 m)', type: 'spreader', workWidthM: 36, loadCapacityT: 2.2 },
      { name: 'Bogballe E2W (36 m)', type: 'spreader', workWidthM: 36, loadCapacityT: 2.0 },
    ],
  },
  {
    label: 'Sklízeče píce / senoseče',
    emoji: '🌾',
    items: [
      { name: 'Claas Disco 3200 FC (3.2 m)', type: 'mower', workWidthM: 3.2 },
      { name: 'Claas Disco 3500 FC (3.5 m)', type: 'mower', workWidthM: 3.5 },
      { name: 'Pöttinger Novacat 301 (3 m)', type: 'mower', workWidthM: 3.0 },
      { name: 'Pöttinger Novacat 351 (3.5 m)', type: 'mower', workWidthM: 3.5 },
      { name: 'Pöttinger Novacat 306 Alpha (3 m)', type: 'mower', workWidthM: 3.0 },
      { name: 'Pöttinger Novacat 352 Alpha (3.5 m)', type: 'mower', workWidthM: 3.5 },
      { name: 'Pöttinger Novacat X8 (přední, 3.1 m)', type: 'mower', workWidthM: 3.1 },
      { name: 'Kuhn FC 313 (3.1 m)', type: 'mower', workWidthM: 3.1 },
      { name: 'Kverneland 4332 FT (3.3 m)', type: 'mower', workWidthM: 3.3 },
      { name: 'Claas Volto 900 (obracecí, 9 m)', type: 'mower', workWidthM: 9.0 },
      { name: 'Claas Liner 4000 (shrnovač, 4 m)', type: 'mower', workWidthM: 4.0 },
      { name: 'Pöttinger TOP 952 A (obracecí, 9.5 m)', type: 'mower', workWidthM: 9.5 },
      { name: 'Pöttinger TOP 1252 A (obracecí, 12.5 m)', type: 'mower', workWidthM: 12.5 },
      { name: 'Pöttinger HIT 9.14 (shrnovač, 9 m)', type: 'mower', workWidthM: 9.0 },
      { name: 'Pöttinger HIT 12.14 (shrnovač, 12 m)', type: 'mower', workWidthM: 12.0 },
    ],
  },
  {
    label: 'Lisy / balíkovačky',
    emoji: '🟤',
    items: [
      { name: 'Claas Rollant 374 RC (kulatý balík)', type: 'baler' },
      { name: 'Claas Rollant 454 RC (kulatý balík)', type: 'baler' },
      { name: 'Pöttinger Impress 125 V (kulatý balík)', type: 'baler' },
      { name: 'Pöttinger Impress 155 V (kulatý balík)', type: 'baler' },
      { name: 'Pöttinger Impress 185 V (kulatý balík)', type: 'baler' },
      { name: 'Pöttinger Impress 185 FC Pro (kulatý balík)', type: 'baler' },
      { name: 'Pöttinger Master 100 (kulatý balík)', type: 'baler' },
      { name: 'Pöttinger Master 200 VC (kulatý balík)', type: 'baler' },
      { name: 'Krone Comprima F125 XC (kulatý balík)', type: 'baler' },
      { name: 'New Holland Roll-Belt 150 (kulatý balík)', type: 'baler' },
      { name: 'Claas Quadrant 5300 (hranolovací)', type: 'baler' },
      { name: 'Pöttinger Jumbo 7210 (sklízeč-lis)', type: 'baler' },
      { name: 'Krone Big Pack 1290 (hranolovací)', type: 'baler' },
    ],
  },
  {
    label: 'Kejdové cisterny',
    emoji: '🪣',
    items: [
      { name: 'Joskin Modulo 2 8000 (8 m³)', type: 'slurry', loadCapacityT: 8.0 },
      { name: 'Joskin Modulo 2 12000 (12 m³)', type: 'slurry', loadCapacityT: 12.0 },
      { name: 'Bauer Rotastream (6 m³)', type: 'slurry', loadCapacityT: 6.0 },
      { name: 'Samson SG 18 (18 m³)', type: 'slurry', loadCapacityT: 18.0 },
      { name: 'Zunhammer SKE 15 PU (15 m³)', type: 'slurry', loadCapacityT: 15.0 },
      { name: 'Fliegl VFW 16000 (16 m³)', type: 'slurry', loadCapacityT: 16.0 },
    ],
  },
  {
    label: 'Přívěsy / valníky',
    emoji: '🚛',
    items: [
      { name: 'Joskin Trans-Space 7500 (7.5 t)', type: 'trailer', loadCapacityT: 7.5 },
      { name: 'Joskin Trans-Space 10000 (10 t)', type: 'trailer', loadCapacityT: 10.0 },
      { name: 'Fliegl DPW 180 (18 t)', type: 'trailer', loadCapacityT: 18.0 },
      { name: 'Fliegl ASW 271 (27 t)', type: 'trailer', loadCapacityT: 27.0 },
      { name: 'Krampe Big Body 540 (20 t)', type: 'trailer', loadCapacityT: 20.0 },
      { name: 'Brantner TA 23071 (22 t)', type: 'trailer', loadCapacityT: 22.0 },
    ],
  },
  {
    label: 'Nakladače',
    emoji: '🏗️',
    items: [
      { name: 'Manitou MLT 625 (2.5 t)', type: 'loader', loadCapacityT: 2.5 },
      { name: 'Manitou MLT 735 (3.5 t)', type: 'loader', loadCapacityT: 3.5 },
      { name: 'JCB 531-70 (3.1 t)', type: 'loader', loadCapacityT: 3.1 },
      { name: 'Merlo Multifarmer 30.6 (3 t)', type: 'loader', loadCapacityT: 3.0 },
      { name: 'Claas Scorpion 756 (3.5 t)', type: 'loader', loadCapacityT: 3.5 },
    ],
  },
];
